name: First Pipeline

on:
  
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: posts-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306: 3306
        options: --health-cmd="mysqladmin ping"

steps:
  - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    with:
      php-version: '8.1'

  - uses: actions/checkout@v3

  - name: Copy .env
    run: cp .env.ci .env

  - name: Install Dependencies
    run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

  - name: Generate Key
    run: php artisan key:generate

  - name: Directory Permissions
    run: chmod -R storage bootstrap/cache

  - name: phpstan
    run: ./vendor/bib/phpstan analyse --memory-limit=1G

  - name: Run Test
    run: php artisan test

























